# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'camera_error_dialog_design.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtWidgets


class Ui_camera_error_dialog(object):
    def setupUi(self, camera_error_dialog):
        camera_error_dialog.setObjectName("camera_error_dialog")
        camera_error_dialog.resize(400, 150)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(camera_error_dialog.sizePolicy().hasHeightForWidth())
        camera_error_dialog.setSizePolicy(sizePolicy)
        camera_error_dialog.setMinimumSize(QtCore.QSize(400, 150))
        camera_error_dialog.setMaximumSize(QtCore.QSize(400, 150))
        self.verticalLayout = QtWidgets.QVBoxLayout(camera_error_dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.error_text = QtWidgets.QLabel(camera_error_dialog)
        self.error_text.setWordWrap(True)
        self.error_text.setObjectName("error_text")
        self.verticalLayout.addWidget(self.error_text)
        self.ok_button = QtWidgets.QDialogButtonBox(camera_error_dialog)
        self.ok_button.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.ok_button.setObjectName("ok_button")
        self.verticalLayout.addWidget(self.ok_button)

        self.retranslateUi(camera_error_dialog)
        QtCore.QMetaObject.connectSlotsByName(camera_error_dialog)

    def retranslateUi(self, camera_error_dialog):
        _translate = QtCore.QCoreApplication.translate
        camera_error_dialog.setWindowTitle(_translate("camera_error_dialog", "Ой!"))
        self.error_text.setText(_translate("camera_error_dialog", "Возникла ошибка при получении доступа к веб-камере. Пожалуйста, проверьте наличие подключения веб-камеры к устройству или воспользуйтесь выбором изображения при отсутствии камеры."))
